name: Deploy React

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Atualizar código no WSL
        run: |
          cd /home/andersonmoura/producao/Monitoramentos/habibs_esfihas
          git pull origin main

      - name: Rebuild e reiniciar container
        run: |
          cd /home/andersonmoura/producao/AirFlow
          docker compose build habibs-esfihas
          docker compose up -d habibs-esfihas
