name: Deploy React

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Baixar código atualizado
        uses: actions/checkout@v4

      - name: Copiar para WSL e reiniciar container
        run: |
          cp -r . /home/andersonmoura/producao/habibs_esfihas/
          cd /home/andersonmoura/producao/AirFlow
          docker compose build habibs-esfihas
          docker compose up -d habibs-esfihas
